--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.8.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 11. 16. 18:10:20
-- Server version: 10.4.24
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `14ke_kesok`;

--
-- Drop table `failed_jobs`
--
DROP TABLE IF EXISTS failed_jobs;

--
-- Drop table `migrations`
--
DROP TABLE IF EXISTS migrations;

--
-- Drop table `my_classes`
--
DROP TABLE IF EXISTS my_classes;

--
-- Drop table `password_reset_tokens`
--
DROP TABLE IF EXISTS password_reset_tokens;

--
-- Drop table `personal_access_tokens`
--
DROP TABLE IF EXISTS personal_access_tokens;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE `14ke_kesok`;

--
-- Create table `users`
--
CREATE TABLE users (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  email_verified_at TIMESTAMP NULL DEFAULT NULL,
  password VARCHAR(255) NOT NULL,
  remember_token VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `users_email_unique` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX users_email_unique(email);

--
-- Create table `personal_access_tokens`
--
CREATE TABLE personal_access_tokens (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  tokenable_type VARCHAR(255) NOT NULL,
  tokenable_id BIGINT(20) UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  token VARCHAR(64) NOT NULL,
  abilities TEXT DEFAULT NULL,
  last_used_at TIMESTAMP NULL DEFAULT NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `personal_access_tokens_token_unique` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD UNIQUE INDEX personal_access_tokens_token_unique(token);

--
-- Create index `personal_access_tokens_tokenable_type_tokenable_id_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_tokenable_type_tokenable_id_index(tokenable_type, tokenable_id);

--
-- Create table `password_reset_tokens`
--
CREATE TABLE password_reset_tokens (
  email VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (email)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `my_classes`
--
CREATE TABLE my_classes (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  classname VARCHAR(10) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 27,
AVG_ROW_LENGTH = 630,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `migrations`
--
CREATE TABLE migrations (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  migration VARCHAR(255) NOT NULL,
  batch INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 56,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `failed_jobs`
--
CREATE TABLE failed_jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  queue TEXT NOT NULL,
  payload LONGTEXT NOT NULL,
  exception LONGTEXT NOT NULL,
  failed_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `failed_jobs_uuid_unique` on table `failed_jobs`
--
ALTER TABLE failed_jobs 
  ADD UNIQUE INDEX failed_jobs_uuid_unique(uuid);

-- 
-- Dumping data for table users
--
-- Table `14ke_kesok`.users does not contain any data (it is empty)

-- 
-- Dumping data for table personal_access_tokens
--
-- Table `14ke_kesok`.personal_access_tokens does not contain any data (it is empty)

-- 
-- Dumping data for table password_reset_tokens
--
-- Table `14ke_kesok`.password_reset_tokens does not contain any data (it is empty)

-- 
-- Dumping data for table my_classes
--
INSERT INTO my_classes VALUES
(1, '8. A', '2023-11-16 16:59:43', '2023-11-16 17:05:32'),
(2, '9. B', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(3, '9. C', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(4, '9. D', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(5, '9. E', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(6, '10. A', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(7, '10. B', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(8, '10. C', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(9, '10. D', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(10, '10. E', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(11, '11. A', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(12, '11. B', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(13, '11. C', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(14, '11. D', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(15, '11. E', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(16, '12. A', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(17, '12. B', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(18, '12. C', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(19, '12. D', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(20, '12. E', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(21, '13. A', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(22, '13. B', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(23, '13. C', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(24, '13. D', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(25, '13. E', '2023-11-16 16:59:43', '2023-11-16 16:59:43'),
(26, '14. A', '2023-11-16 16:59:50', '2023-11-16 16:59:50');

-- 
-- Dumping data for table migrations
--
INSERT INTO migrations VALUES
(51, '2014_10_12_000000_create_users_table', 1),
(52, '2014_10_12_100000_create_password_reset_tokens_table', 1),
(53, '2019_08_19_000000_create_failed_jobs_table', 1),
(54, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(55, '2023_11_16_143149_create_my_classes_table', 1);

-- 
-- Dumping data for table failed_jobs
--
-- Table `14ke_kesok`.failed_jobs does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;